macro_rules! q {
    () => {
        quote! {}
    };
}
macro_rules! f {
    ($ s : expr) => {
        String::from($s)
    };
}
macro_rules! e {
    ($ idx : expr , $ s : ident) => {
        $s[$idx].clone()
    };
}
macro_rules! d {
    ($ idx : expr , $ p : ident) => {
        $p[$idx].clone()
    };
}
fn __grammar__() -> Grammar<TestCase, Token, TranslatorStack> {
    let y = vec![
        P::n(
            0usize,
            s(0usize),
            vec![s(2usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            1usize,
            s(2usize),
            vec![s(3usize), s(4usize)],
            Some(f! { "Testing" }),
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Shared::set_body(ast, tl_stack.pop_body());
            })),
        ),
        P::n(
            2usize,
            s(3usize),
            vec![s(5usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                tl_stack.push(TranslatorStack::Body(Body::new()));
            })),
        ),
        P::n(
            3usize,
            s(4usize),
            vec![s(6usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            4usize,
            s(4usize),
            vec![s(6usize), s(4usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            5usize,
            s(6usize),
            vec![s(7usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Driver::NAVIGATE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            6usize,
            s(6usize),
            vec![s(9usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Driver::CLOSE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            7usize,
            s(6usize),
            vec![s(10usize), s(8usize)],
            Some(f! { "Please check teststeps syntax" }),
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Element::CLICK(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            8usize,
            s(6usize),
            vec![s(11usize)],
            Some(f! { "Please check teststeps syntax" }),
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Navigation::BACK(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            9usize,
            s(6usize),
            vec![s(12usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Navigation::FORWARD(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            10usize,
            s(6usize),
            vec![s(13usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Navigation::REFRESH(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            11usize,
            s(6usize),
            vec![s(14usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Timeouts::WAIT(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            12usize,
            s(6usize),
            vec![s(15usize), s(16usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Custom::VAR_DECLARATION(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            13usize,
            s(6usize),
            vec![s(17usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Custom::ASSERT(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            14usize,
            s(6usize),
            vec![s(18usize), s(8usize), s(19usize), s(20usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Element::SENDKEYS(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            15usize,
            s(6usize),
            vec![s(21usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            16usize,
            s(21usize),
            vec![s(22usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::IF(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            17usize,
            s(21usize),
            vec![s(22usize), s(23usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::IF(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            18usize,
            s(21usize),
            vec![s(22usize), s(24usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::IF(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            19usize,
            s(23usize),
            vec![s(25usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::ELSE_IF(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            20usize,
            s(23usize),
            vec![s(25usize), s(23usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::ELSE_IF(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            21usize,
            s(23usize),
            vec![s(25usize), s(24usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::ELSE_IF(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            22usize,
            s(22usize),
            vec![s(26usize), s(8usize), s(27usize), s(4usize), s(28usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            23usize,
            s(25usize),
            vec![
                s(29usize),
                s(26usize),
                s(8usize),
                s(27usize),
                s(4usize),
                s(28usize),
            ],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            24usize,
            s(24usize),
            vec![s(29usize), s(27usize), s(4usize), s(28usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Conditional::ELSE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            25usize,
            s(33usize),
            vec![
                s(30usize),
                s(31usize),
                s(8usize),
                s(32usize),
                s(20usize),
                s(8usize),
            ],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Element::GET_ATTRIBUTE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            26usize,
            s(33usize),
            vec![s(30usize), s(34usize), s(35usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Driver::GET_CURRENT_URL(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            27usize,
            s(33usize),
            vec![s(30usize), s(36usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                Driver::GET_TITLE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            28usize,
            s(8usize),
            vec![s(37usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            29usize,
            s(8usize),
            vec![s(38usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            30usize,
            s(8usize),
            vec![s(39usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            31usize,
            s(8usize),
            vec![s(33usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            32usize,
            s(37usize),
            vec![s(40usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                LiteralExpression::NUMBER(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            33usize,
            s(37usize),
            vec![s(41usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                LiteralExpression::STRING(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            34usize,
            s(37usize),
            vec![s(15usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                LiteralExpression::IDENT(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            35usize,
            s(37usize),
            vec![s(42usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                LiteralExpression::BOOLEAN(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            36usize,
            s(37usize),
            vec![s(43usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                LiteralExpression::BOOLEAN(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            37usize,
            s(39usize),
            vec![s(44usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            38usize,
            s(39usize),
            vec![s(45usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            39usize,
            s(44usize),
            vec![s(46usize), s(45usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                UnaryExpression::NEGATION(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            40usize,
            s(45usize),
            vec![s(47usize), s(8usize), s(48usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                UnaryExpression::GROUPED(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            41usize,
            s(38usize),
            vec![s(49usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            42usize,
            s(38usize),
            vec![s(50usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            43usize,
            s(38usize),
            vec![s(51usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            44usize,
            s(51usize),
            vec![s(8usize), s(52usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::AND(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            45usize,
            s(51usize),
            vec![s(8usize), s(53usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::OR(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            46usize,
            s(49usize),
            vec![s(8usize), s(54usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::EQ(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            47usize,
            s(49usize),
            vec![s(8usize), s(55usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::NE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            48usize,
            s(49usize),
            vec![s(8usize), s(56usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::GT(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            49usize,
            s(49usize),
            vec![s(8usize), s(57usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::LT(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            50usize,
            s(49usize),
            vec![s(8usize), s(58usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::GE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            51usize,
            s(49usize),
            vec![s(8usize), s(59usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::LE(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            52usize,
            s(50usize),
            vec![s(8usize), s(60usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::ADD(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            53usize,
            s(50usize),
            vec![s(8usize), s(61usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::SUB(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            54usize,
            s(50usize),
            vec![s(8usize), s(62usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::MUL(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            55usize,
            s(50usize),
            vec![s(8usize), s(63usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::DIV(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            56usize,
            s(50usize),
            vec![s(8usize), s(64usize), s(8usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                BinaryExpression::REM(ast, token_stack, tl_stack, errors);
            })),
        ),
        P::n(
            57usize,
            s(7usize),
            vec![s(65usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            58usize,
            s(10usize),
            vec![s(66usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            59usize,
            s(11usize),
            vec![s(67usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            60usize,
            s(12usize),
            vec![s(68usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            61usize,
            s(13usize),
            vec![s(69usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            62usize,
            s(30usize),
            vec![s(70usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            63usize,
            s(14usize),
            vec![s(71usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            64usize,
            s(17usize),
            vec![s(72usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            65usize,
            s(18usize),
            vec![s(73usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            66usize,
            s(9usize),
            vec![s(74usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            67usize,
            s(31usize),
            vec![s(75usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            68usize,
            s(20usize),
            vec![s(76usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            69usize,
            s(35usize),
            vec![s(77usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            70usize,
            s(36usize),
            vec![s(78usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            71usize,
            s(80usize),
            vec![s(79usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            72usize,
            s(32usize),
            vec![s(81usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            73usize,
            s(83usize),
            vec![s(82usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            74usize,
            s(19usize),
            vec![s(84usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            75usize,
            s(34usize),
            vec![s(85usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            76usize,
            s(16usize),
            vec![s(86usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            77usize,
            s(46usize),
            vec![s(87usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            78usize,
            s(60usize),
            vec![s(88usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            79usize,
            s(61usize),
            vec![s(89usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            80usize,
            s(62usize),
            vec![s(90usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            81usize,
            s(63usize),
            vec![s(91usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            82usize,
            s(64usize),
            vec![s(92usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            83usize,
            s(54usize),
            vec![s(93usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            84usize,
            s(55usize),
            vec![s(94usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            85usize,
            s(56usize),
            vec![s(95usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            86usize,
            s(57usize),
            vec![s(96usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            87usize,
            s(58usize),
            vec![s(97usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            88usize,
            s(59usize),
            vec![s(98usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            89usize,
            s(52usize),
            vec![s(99usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            90usize,
            s(53usize),
            vec![s(100usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            91usize,
            s(26usize),
            vec![s(101usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            92usize,
            s(29usize),
            vec![s(102usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            93usize,
            s(47usize),
            vec![s(103usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            94usize,
            s(48usize),
            vec![s(104usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            95usize,
            s(27usize),
            vec![s(105usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {
                tl_stack.push(TranslatorStack::Body(Body::new()));
            })),
        ),
        P::n(
            96usize,
            s(28usize),
            vec![s(106usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            97usize,
            s(41usize),
            vec![s(107usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            98usize,
            s(15usize),
            vec![s(108usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            99usize,
            s(40usize),
            vec![s(109usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            100usize,
            s(42usize),
            vec![s(110usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
        P::n(
            101usize,
            s(43usize),
            vec![s(111usize)],
            None,
            quote! {},
            Some(Rc::new(|ast, token_stack, tl_stack, errors| {})),
        ),
    ];
    let x = vec![
        N(f! { "S'" }),
        T(f! { "EOF" }),
        N(f! { "Start" }),
        N(f! { "Testcase" }),
        N(f! { "Teststeps" }),
        T(f! { "testcase" }),
        N(f! { "Teststep" }),
        N(f! { "Navigate" }),
        N(f! { "Expression" }),
        N(f! { "Close" }),
        N(f! { "Click" }),
        N(f! { "Back" }),
        N(f! { "Forward" }),
        N(f! { "Refresh" }),
        N(f! { "Wait" }),
        N(f! { "Ident" }),
        N(f! { "Assign" }),
        N(f! { "Assert" }),
        N(f! { "Enter" }),
        N(f! { "In" }),
        N(f! { "Element" }),
        N(f! { "IfStmt" }),
        N(f! { "IfExpr" }),
        N(f! { "ElseIfStmt" }),
        N(f! { "ElseExpr" }),
        N(f! { "ElseIfExpr" }),
        N(f! { "If" }),
        N(f! { "L_CurlyBrace" }),
        N(f! { "R_CurlyBrace" }),
        N(f! { "Else" }),
        N(f! { "Get" }),
        N(f! { "Attribute" }),
        N(f! { "From" }),
        N(f! { "Getter" }),
        N(f! { "Current" }),
        N(f! { "Url" }),
        N(f! { "Title" }),
        N(f! { "LiteralExpression" }),
        N(f! { "BinaryExpression" }),
        N(f! { "UnaryExpression" }),
        N(f! { "Number" }),
        N(f! { "String" }),
        N(f! { "True" }),
        N(f! { "False" }),
        N(f! { "NegationExpression" }),
        N(f! { "GroupedExpression" }),
        N(f! { "Negation" }),
        N(f! { "Left_paran" }),
        N(f! { "Right_paran" }),
        N(f! { "ComparisionExpression" }),
        N(f! { "ArthimaticExpression" }),
        N(f! { "LogicalExpression" }),
        N(f! { "And" }),
        N(f! { "Or" }),
        N(f! { "Equality" }),
        N(f! { "Not_equal" }),
        N(f! { "Greater_than" }),
        N(f! { "Lesser_than" }),
        N(f! { "Greater_than_equal" }),
        N(f! { "Lesser_than_equal" }),
        N(f! { "Plus" }),
        N(f! { "Minus" }),
        N(f! { "Multiply" }),
        N(f! { "Forward_slash" }),
        N(f! { "Modulus" }),
        T(f! { "navigate" }),
        T(f! { "click" }),
        T(f! { "back" }),
        T(f! { "forward" }),
        T(f! { "refresh" }),
        T(f! { "get" }),
        T(f! { "wait" }),
        T(f! { "assert" }),
        T(f! { "enter" }),
        T(f! { "close" }),
        T(f! { "attribute" }),
        T(f! { "element" }),
        T(f! { "url" }),
        T(f! { "title" }),
        T(f! { "var" }),
        N(f! { "Var" }),
        T(f! { "from" }),
        T(f! { "to" }),
        N(f! { "To" }),
        T(f! { "in" }),
        T(f! { "current" }),
        T(f! { "'='" }),
        T(f! { "'!'" }),
        T(f! { "'+'" }),
        T(f! { "'-'" }),
        T(f! { "'*'" }),
        T(f! { "'/'" }),
        T(f! { "'%'" }),
        T(f! { "\"==\"" }),
        T(f! { "\"!=\"" }),
        T(f! { "'>'" }),
        T(f! { "'<'" }),
        T(f! { "\">=\"" }),
        T(f! { "\"<=\"" }),
        T(f! { "and" }),
        T(f! { "or" }),
        T(f! { "if" }),
        T(f! { "else" }),
        T(f! { "'('" }),
        T(f! { "')'" }),
        T(f! { "'{'" }),
        T(f! { "'}'" }),
        T(f! { "string" }),
        T(f! { "identifier" }),
        T(f! { "number" }),
        T(f! { "true" }),
        T(f! { "false" }),
    ];
    Grammar {
        start: s(2usize),
        productions: Productions {
            map: IndexMap::from([
                (d! { 0usize , y }, p(0usize)),
                (d! { 1usize , y }, p(1usize)),
                (d! { 2usize , y }, p(2usize)),
                (d! { 3usize , y }, p(3usize)),
                (d! { 4usize , y }, p(4usize)),
                (d! { 5usize , y }, p(5usize)),
                (d! { 6usize , y }, p(6usize)),
                (d! { 7usize , y }, p(7usize)),
                (d! { 8usize , y }, p(8usize)),
                (d! { 9usize , y }, p(9usize)),
                (d! { 10usize , y }, p(10usize)),
                (d! { 11usize , y }, p(11usize)),
                (d! { 12usize , y }, p(12usize)),
                (d! { 13usize , y }, p(13usize)),
                (d! { 14usize , y }, p(14usize)),
                (d! { 15usize , y }, p(15usize)),
                (d! { 16usize , y }, p(16usize)),
                (d! { 17usize , y }, p(17usize)),
                (d! { 18usize , y }, p(18usize)),
                (d! { 19usize , y }, p(19usize)),
                (d! { 20usize , y }, p(20usize)),
                (d! { 21usize , y }, p(21usize)),
                (d! { 22usize , y }, p(22usize)),
                (d! { 23usize , y }, p(23usize)),
                (d! { 24usize , y }, p(24usize)),
                (d! { 25usize , y }, p(25usize)),
                (d! { 26usize , y }, p(26usize)),
                (d! { 27usize , y }, p(27usize)),
                (d! { 28usize , y }, p(28usize)),
                (d! { 29usize , y }, p(29usize)),
                (d! { 30usize , y }, p(30usize)),
                (d! { 31usize , y }, p(31usize)),
                (d! { 32usize , y }, p(32usize)),
                (d! { 33usize , y }, p(33usize)),
                (d! { 34usize , y }, p(34usize)),
                (d! { 35usize , y }, p(35usize)),
                (d! { 36usize , y }, p(36usize)),
                (d! { 37usize , y }, p(37usize)),
                (d! { 38usize , y }, p(38usize)),
                (d! { 39usize , y }, p(39usize)),
                (d! { 40usize , y }, p(40usize)),
                (d! { 41usize , y }, p(41usize)),
                (d! { 42usize , y }, p(42usize)),
                (d! { 43usize , y }, p(43usize)),
                (d! { 44usize , y }, p(44usize)),
                (d! { 45usize , y }, p(45usize)),
                (d! { 46usize , y }, p(46usize)),
                (d! { 47usize , y }, p(47usize)),
                (d! { 48usize , y }, p(48usize)),
                (d! { 49usize , y }, p(49usize)),
                (d! { 50usize , y }, p(50usize)),
                (d! { 51usize , y }, p(51usize)),
                (d! { 52usize , y }, p(52usize)),
                (d! { 53usize , y }, p(53usize)),
                (d! { 54usize , y }, p(54usize)),
                (d! { 55usize , y }, p(55usize)),
                (d! { 56usize , y }, p(56usize)),
                (d! { 57usize , y }, p(57usize)),
                (d! { 58usize , y }, p(58usize)),
                (d! { 59usize , y }, p(59usize)),
                (d! { 60usize , y }, p(60usize)),
                (d! { 61usize , y }, p(61usize)),
                (d! { 62usize , y }, p(62usize)),
                (d! { 63usize , y }, p(63usize)),
                (d! { 64usize , y }, p(64usize)),
                (d! { 65usize , y }, p(65usize)),
                (d! { 66usize , y }, p(66usize)),
                (d! { 67usize , y }, p(67usize)),
                (d! { 68usize , y }, p(68usize)),
                (d! { 69usize , y }, p(69usize)),
                (d! { 70usize , y }, p(70usize)),
                (d! { 71usize , y }, p(71usize)),
                (d! { 72usize , y }, p(72usize)),
                (d! { 73usize , y }, p(73usize)),
                (d! { 74usize , y }, p(74usize)),
                (d! { 75usize , y }, p(75usize)),
                (d! { 76usize , y }, p(76usize)),
                (d! { 77usize , y }, p(77usize)),
                (d! { 78usize , y }, p(78usize)),
                (d! { 79usize , y }, p(79usize)),
                (d! { 80usize , y }, p(80usize)),
                (d! { 81usize , y }, p(81usize)),
                (d! { 82usize , y }, p(82usize)),
                (d! { 83usize , y }, p(83usize)),
                (d! { 84usize , y }, p(84usize)),
                (d! { 85usize , y }, p(85usize)),
                (d! { 86usize , y }, p(86usize)),
                (d! { 87usize , y }, p(87usize)),
                (d! { 88usize , y }, p(88usize)),
                (d! { 89usize , y }, p(89usize)),
                (d! { 90usize , y }, p(90usize)),
                (d! { 91usize , y }, p(91usize)),
                (d! { 92usize , y }, p(92usize)),
                (d! { 93usize , y }, p(93usize)),
                (d! { 94usize , y }, p(94usize)),
                (d! { 95usize , y }, p(95usize)),
                (d! { 96usize , y }, p(96usize)),
                (d! { 97usize , y }, p(97usize)),
                (d! { 98usize , y }, p(98usize)),
                (d! { 99usize , y }, p(99usize)),
                (d! { 100usize , y }, p(100usize)),
                (d! { 101usize , y }, p(101usize)),
            ]),
            vec: y,
        },
        production_head_map: IndexMap::new(),
        symbols: Symbols {
            map: IndexMap::from([
                (e! { 0usize , x }, s(0usize)),
                (e! { 1usize , x }, s(1usize)),
                (e! { 2usize , x }, s(2usize)),
                (e! { 3usize , x }, s(3usize)),
                (e! { 4usize , x }, s(4usize)),
                (e! { 5usize , x }, s(5usize)),
                (e! { 6usize , x }, s(6usize)),
                (e! { 7usize , x }, s(7usize)),
                (e! { 8usize , x }, s(8usize)),
                (e! { 9usize , x }, s(9usize)),
                (e! { 10usize , x }, s(10usize)),
                (e! { 11usize , x }, s(11usize)),
                (e! { 12usize , x }, s(12usize)),
                (e! { 13usize , x }, s(13usize)),
                (e! { 14usize , x }, s(14usize)),
                (e! { 15usize , x }, s(15usize)),
                (e! { 16usize , x }, s(16usize)),
                (e! { 17usize , x }, s(17usize)),
                (e! { 18usize , x }, s(18usize)),
                (e! { 19usize , x }, s(19usize)),
                (e! { 20usize , x }, s(20usize)),
                (e! { 21usize , x }, s(21usize)),
                (e! { 22usize , x }, s(22usize)),
                (e! { 23usize , x }, s(23usize)),
                (e! { 24usize , x }, s(24usize)),
                (e! { 25usize , x }, s(25usize)),
                (e! { 26usize , x }, s(26usize)),
                (e! { 27usize , x }, s(27usize)),
                (e! { 28usize , x }, s(28usize)),
                (e! { 29usize , x }, s(29usize)),
                (e! { 30usize , x }, s(30usize)),
                (e! { 31usize , x }, s(31usize)),
                (e! { 32usize , x }, s(32usize)),
                (e! { 33usize , x }, s(33usize)),
                (e! { 34usize , x }, s(34usize)),
                (e! { 35usize , x }, s(35usize)),
                (e! { 36usize , x }, s(36usize)),
                (e! { 37usize , x }, s(37usize)),
                (e! { 38usize , x }, s(38usize)),
                (e! { 39usize , x }, s(39usize)),
                (e! { 40usize , x }, s(40usize)),
                (e! { 41usize , x }, s(41usize)),
                (e! { 42usize , x }, s(42usize)),
                (e! { 43usize , x }, s(43usize)),
                (e! { 44usize , x }, s(44usize)),
                (e! { 45usize , x }, s(45usize)),
                (e! { 46usize , x }, s(46usize)),
                (e! { 47usize , x }, s(47usize)),
                (e! { 48usize , x }, s(48usize)),
                (e! { 49usize , x }, s(49usize)),
                (e! { 50usize , x }, s(50usize)),
                (e! { 51usize , x }, s(51usize)),
                (e! { 52usize , x }, s(52usize)),
                (e! { 53usize , x }, s(53usize)),
                (e! { 54usize , x }, s(54usize)),
                (e! { 55usize , x }, s(55usize)),
                (e! { 56usize , x }, s(56usize)),
                (e! { 57usize , x }, s(57usize)),
                (e! { 58usize , x }, s(58usize)),
                (e! { 59usize , x }, s(59usize)),
                (e! { 60usize , x }, s(60usize)),
                (e! { 61usize , x }, s(61usize)),
                (e! { 62usize , x }, s(62usize)),
                (e! { 63usize , x }, s(63usize)),
                (e! { 64usize , x }, s(64usize)),
                (e! { 65usize , x }, s(65usize)),
                (e! { 66usize , x }, s(66usize)),
                (e! { 67usize , x }, s(67usize)),
                (e! { 68usize , x }, s(68usize)),
                (e! { 69usize , x }, s(69usize)),
                (e! { 70usize , x }, s(70usize)),
                (e! { 71usize , x }, s(71usize)),
                (e! { 72usize , x }, s(72usize)),
                (e! { 73usize , x }, s(73usize)),
                (e! { 74usize , x }, s(74usize)),
                (e! { 75usize , x }, s(75usize)),
                (e! { 76usize , x }, s(76usize)),
                (e! { 77usize , x }, s(77usize)),
                (e! { 78usize , x }, s(78usize)),
                (e! { 79usize , x }, s(79usize)),
                (e! { 80usize , x }, s(80usize)),
                (e! { 81usize , x }, s(81usize)),
                (e! { 82usize , x }, s(82usize)),
                (e! { 83usize , x }, s(83usize)),
                (e! { 84usize , x }, s(84usize)),
                (e! { 85usize , x }, s(85usize)),
                (e! { 86usize , x }, s(86usize)),
                (e! { 87usize , x }, s(87usize)),
                (e! { 88usize , x }, s(88usize)),
                (e! { 89usize , x }, s(89usize)),
                (e! { 90usize , x }, s(90usize)),
                (e! { 91usize , x }, s(91usize)),
                (e! { 92usize , x }, s(92usize)),
                (e! { 93usize , x }, s(93usize)),
                (e! { 94usize , x }, s(94usize)),
                (e! { 95usize , x }, s(95usize)),
                (e! { 96usize , x }, s(96usize)),
                (e! { 97usize , x }, s(97usize)),
                (e! { 98usize , x }, s(98usize)),
                (e! { 99usize , x }, s(99usize)),
                (e! { 100usize , x }, s(100usize)),
                (e! { 101usize , x }, s(101usize)),
                (e! { 102usize , x }, s(102usize)),
                (e! { 103usize , x }, s(103usize)),
                (e! { 104usize , x }, s(104usize)),
                (e! { 105usize , x }, s(105usize)),
                (e! { 106usize , x }, s(106usize)),
                (e! { 107usize , x }, s(107usize)),
                (e! { 108usize , x }, s(108usize)),
                (e! { 109usize , x }, s(109usize)),
                (e! { 110usize , x }, s(110usize)),
                (e! { 111usize , x }, s(111usize)),
            ]),
            vec: x,
            terminals: vec![
                s(1usize),
                s(5usize),
                s(65usize),
                s(66usize),
                s(67usize),
                s(68usize),
                s(69usize),
                s(70usize),
                s(71usize),
                s(72usize),
                s(73usize),
                s(74usize),
                s(75usize),
                s(76usize),
                s(77usize),
                s(78usize),
                s(79usize),
                s(81usize),
                s(82usize),
                s(84usize),
                s(85usize),
                s(86usize),
                s(87usize),
                s(88usize),
                s(89usize),
                s(90usize),
                s(91usize),
                s(92usize),
                s(93usize),
                s(94usize),
                s(95usize),
                s(96usize),
                s(97usize),
                s(98usize),
                s(99usize),
                s(100usize),
                s(101usize),
                s(102usize),
                s(103usize),
                s(104usize),
                s(105usize),
                s(106usize),
                s(107usize),
                s(108usize),
                s(109usize),
                s(110usize),
                s(111usize),
            ],
            non_terminals: vec![
                s(0usize),
                s(2usize),
                s(3usize),
                s(4usize),
                s(6usize),
                s(7usize),
                s(8usize),
                s(9usize),
                s(10usize),
                s(11usize),
                s(12usize),
                s(13usize),
                s(14usize),
                s(15usize),
                s(16usize),
                s(17usize),
                s(18usize),
                s(19usize),
                s(20usize),
                s(21usize),
                s(22usize),
                s(23usize),
                s(24usize),
                s(25usize),
                s(26usize),
                s(27usize),
                s(28usize),
                s(29usize),
                s(30usize),
                s(31usize),
                s(32usize),
                s(33usize),
                s(34usize),
                s(35usize),
                s(36usize),
                s(37usize),
                s(38usize),
                s(39usize),
                s(40usize),
                s(41usize),
                s(42usize),
                s(43usize),
                s(44usize),
                s(45usize),
                s(46usize),
                s(47usize),
                s(48usize),
                s(49usize),
                s(50usize),
                s(51usize),
                s(52usize),
                s(53usize),
                s(54usize),
                s(55usize),
                s(56usize),
                s(57usize),
                s(58usize),
                s(59usize),
                s(60usize),
                s(61usize),
                s(62usize),
                s(63usize),
                s(64usize),
                s(80usize),
                s(83usize),
            ],
        },
    }
}
